# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            AR
tagline:          'A Development Blog'
description:      'A developer at Validic focusing on code maintainability.  Find me on github <a href="http://github.com/allcentury" target="_blank">@allcentury</a>.'
url:              allcentury.github.io
baseurl:          /hyde/

author:
  name:           'Anthony Ross'
  url:            https://twitter.com/allcentury

paginate:         5

# Custom vars
version:          2.1.0

github:           https://github.com/allcentury
