# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            AR
tagline:          'A Development Blog'
description:      'A developer at Brex focusing on Fintech.  Find me on github <a href="http://github.com/allcentury" target="_blank">@allcentury</a>.'
baseurl:          /

author:
  name:           'Anthony Ross'
  stacko:         http://stackoverflow.com/users/3109182/anthony

paginate:         5

# Custom vars
version:          2.1.0
gems: [jekyll-paginate]

github:           https://github.com/allcentury

plugins:
  - jekyll-paginate
