# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            AR
tagline:          'A Development Blog'
description:      'A developer at commercetools focusing on microservices and code maintainability.  Find me on github <a href="http://github.com/allcentury" target="_blank">@allcentury</a>.'
url:              http://allcentury.github.io
baseurl:          /

author:
  name:           'Anthony Ross'
  url:            https://twitter.com/anthonysross
  stacko:         http://stackoverflow.com/users/3109182/anthony

paginate:         5

# Custom vars
version:          2.1.0

github:           https://github.com/allcentury
